# ~/.config/yazi/theme.toml

[flavor]
dark = "tokyonight-night"

[mgr]
cwd = { fg = "#a9b1d6", italic = true }

# Hovered
hovered = { fg = "black", bg = "lightblue" }
preview_hovered = { bg = "#292e42" }

# Find
find_keyword  = { fg = "#16161e", bg = "#ff9e64", bold = true }
find_position = { fg = "#0db9d7", bg = "#192b38", bold = true }

# Marker
marker_copied   = { fg = "#73daca", bg = "#73daca" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#bb9af7", bg = "#bb9af7" }
marker_selected = { fg = "#7aa2f7", bg = "#7aa2f7" }

# Count
count_copied   = { fg = "#c0caf5", bg = "#41a6b5" }
count_cut      = { fg = "#c0caf5", bg = "#db4b4b" }
count_selected = { fg = "#c0caf5", bg = "#3d59a1" }

# Border
border_symbol = "│"
border_style  = { fg = "#27a1b9" }

# Tab
[tabs]
active   = { fg = "#15161e", bg = "#7aa2f7" }
inactive = { fg = "#7aa2f7", bg = "#3b4261" }

[filetype]
rules = [
    { mime = "directory", fg = "blue", bold = true },
    { mime = "image/*", fg = "magenta" },
    { mime = "video/*", fg = "yellow" },
    { url = "*.pdf", fg = "#ff7f7f" },
    { url = "*.sh", fg = "lightgreen" },
    # { url = "*.toml", fg = "green" },
    # { url = "*.py", fg = "lightblue" },
]
