# ~/.config/yazi/yazi.toml

[env]
PATH = "/usr/local/bin:/usr/bin:/bin"

[mgr]
show_hidden = false
# ratio = [1,2,2]

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = " Nvim", block = true, for = "unix" },
]
newwindow = [
    # { run = '${TERM:-kitty} ${EDITOR:-nvim} "$@"', desc = " Nvim in new window", orphan = true, for = "unix" },
	{ run = '${TERM_CMD:-kitty} ${EDITOR:-nvim} "$@"', desc = " Nvim in new window", orphan = true, for = "unix" }
]
open = [
    { run = 'xdg-open "$1"', desc = " Open", for = "linux" },
]
reveal = [
    { run = 'xdg-open "$(dirname "$1")"', desc = " Reveal", for = "linux" }
]
extract = [
    { run = 'ya pub extract --list "$@"', desc = " Extract here", for = "unix" },
    { run = 'ouch d -y "$@"',             desc = "Extract here with ouch", for = "unix" },
]
pdf = [
    { run = '/usr/bin/zathura "$1"', desc = " Zathura", orphan = true, for = "linux" },
    { run = 'okular "$1"', desc = " Okular", orphan = true, for = "linux" },
    { run = 'evince "$1"', desc = " Evince", orphan = true, for = "linux" },
    # { run = 'QT_QPA_PLATFORM=wayland flatpak run com.github.ahrm.sioyek "$1"', desc = " Sioyek", orphan = true, for = "linux" },
]
images = [
    { run = 'sxiv "$1" $(find "$(dirname "$1")" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | sort)', desc = " SXIV Gallery", orphan = true, for = "linux" },
    { run = 'eog "$1"', desc = " Eye Of Gnome (SVG)", orphan = true, for = "linux" },
    # { run = 'shotwell "$1"', desc = "  Shotwell", orphan = true, for = "linux" },
    # { run = 'aseprite "$1"', desc = " Aseprite (SVG)", orphan = true, for = "linux" },
]
video = [
    { run = 'vlc "$1"', desc = " VLC Player", orphan = true, for = "linux" },
]

[open]
# This tells Yazi to use the "edit" opener for text and "open" for everything else
prepend_rules = [
    # { name = "*/", use = [ "newwindow", "edit", "open", "reveal" ] },
    # { mime = "text/*", use = [ "newwindow", "edit", "reveal" ] },
    # { name = "*.md", use = [ "newwindow", "edit", "reveal" ] },
    # { name = "*.markdown", use = [ "newwindow", "edit", "reveal" ] },
    { name = "*/", use = [ "edit", "open", "reveal", "newwindow" ] },
    { mime = "text/*", use = [ "edit", "reveal", "newwindow" ] },
    { name = "*.md", use = [ "edit", "reveal", "newwindow" ] },
    { name = "*.markdown", use = [ "edit", "reveal", "newwindow" ] },
    { url = "*.{py,c,cpp,h,hpp,rs,js,ts,go,lua,sh}", use = [ "edit", "reveal" ] },
    { mime = "application/pdf", use = [ "pdf" , "reveal" ] },
    { mime = "image/jpeg", use = [ "images", "reveal" ] },
    { mime = "image/png", use = [ "images", "reveal" ] },
    { mime = "image/gif", use = [ "images", "reveal" ] },
    { mime = "image/svg+xml", use = [ "images", "reveal" ] },
    { mime = "video/mp4", use = [ "video", "reveal" ] },
]

[preview]
max_preview_size = 100

prepend_previewers = [
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run  = "ouch"},
  { mime = 'audio/mpegurl', run = 'code' }, # ignore .m3u files
  { mime = "audio/mp3", run = "preview-audio" },
  { mime = "audio/mpeg", run = "preview-audio" },
  { mime = "audio/flac", run = "preview-audio" },
  { mime = "audio/ogg",  run = "preview-audio" },
  { mime = "audio/*",    run = "preview-audio" },  # fallback
]

[[preview.rules]]
name = "*.tif"
run  = "noop"

[[preview.rules]]
name = "*.tiff"
run  = "noop"

[plugin]
mime_detector = "mime-ext"
prepend_previewers = [
   { url = '**/.git/', run = 'preview-git' },
# 	# Change the top-level archive icon
# 	{ ..., run = "ouch --archive-icon='🗄️ '" },
# 	# Or remove it by setting it to ''
# 	{ ..., run = "ouch --archive-icon=''" },
#
# 	# Enable file icons
# 	{ ..., run = "ouch --show-file-icons" },
#
# 	# Disable tree view
# 	{ ..., run = "ouch --list-view" },
#
# 	# These can be combined
# 	{ ..., run = "ouch --archive-icon='🗄️ ' --show-file-icons --list-view" },
]

