#!/usr/bin/env bash

## Author  : Harshit Prahant Dhanwalkar
## Github  : @Harshit-Dhanwalkar

: <<'END_COMMENT'
How to use sxiv selection:
    Run the script / Bing key in Sway config 
    - `sxiv` will open in thumbnail mode showing all wallpapers
    - Press `m` to mark the images you want to select (marked images will have a red border)
    - Press `q` to quit - sxiv will output the paths of marked images
    The script will use the first marked image as your wallpaper

Alternative sxiv keybindings:
    - `Enter` - Open image in full view (press `q` to return to thumbnails)
    - `m` - Mark/unmark image for selection
    - `q` - Quit and output marked files
    - `Ctrl+m` - Mark all images
    - `Ctrl+u` - Unmark all images
END_COMMENT

# Configuration
readonly WALLPAPER_DIR="$HOME/Pictures/wallpapers"
readonly SCRIPT_DIR="$HOME/.config/sway/scripts/Wallpaper_swticher"
readonly IMAGE_PATH="$SCRIPT_DIR/images/geometry.png"
readonly SWAY_CONFIG="$HOME/.config/sway/config"
readonly LOG_FILE="/tmp/wallpaper_switcher.log"

# Generate dynamic rasi config
generate_rasi_config() {
    cat >"/tmp/wallpaper_switcher_style.rasi" <<EOF
/**
 * Dynamic Rasi Configuration
 * Generated by wallpaper switcher script
 *
 * Author  : Harshit Prahant Dhanwalkar
 * Github  : @Harshit-Dhanwalkar
 */

* {
    font:                        "JetBrains Mono Nerd Font 10";
    background:                  #101010;
    background-alt:              #252525;
    foreground:                  #FFFFFF;
    selected:                    #505050;
    active:                      #909090;
    urgent:                      #707070;
}

window {
    transparency:                "real";
    location:                    east;
    anchor:                      east;
    fullscreen:                  false;
    width:                       400px;
    height:                      100%;
    x-offset:                    0px;
    y-offset:                    28px;
    border-radius:               5px;
    cursor:                      "default";
    background-color:            @background;
}

mainbox {
    spacing:                     0px;
    background-color:            transparent;
    orientation:                 vertical;
    children:                    [ "inputbar", "listbox", "mode-switcher" ];
}

listbox {
    spacing:                     10px;
    padding:                     10px;
    background-color:            transparent;
    orientation:                 vertical;
    children:                    [ "message", "listview" ];
}

inputbar {
    spacing:                     10px;
    padding:                     10px 40px 180px;
    border-radius:               0px;
    background-color:            transparent;
    background-image:            url("$IMAGE_PATH", width);
    text-color:                  @foreground;
    orientation:                 horizontal;
    children:                    [ "textbox-prompt-colon", "entry" ];
}

textbox-prompt-colon {
    expand:                      false;
    str:                         " ";
    padding:                     10px 15px;
    border-radius:               15px;
    background-color:            @background-alt;
    text-color:                  inherit;
}

entry {
    expand:                      true;
    padding:                     10px 20px;
    border-radius:               10px;
    background-color:            @background-alt;
    text-color:                  inherit;
    cursor:                      text;
    placeholder:                 "Search through wallpapers";
    placeholder-color:           inherit;
}

listview {
    columns:                     2;
    lines:                       25;
    cycle:                       true;
    dynamic:                     true;
    scrollbar:                   false;
    layout:                      vertical;
    reverse:                     false;
    fixed-height:                true;
    fixed-columns:               false;
    spacing:                     3px;
    background-color:            transparent;
    text-color:                  @foreground;
    cursor:                      "default";
}

element {
    spacing:                     5px;
    padding:                     5px;
    border-radius:               10px;
    background-color:            transparent;
    text-color:                  @foreground;
    cursor:                      pointer;
}

element normal.normal {
    background-color:            inherit;
    text-color:                  inherit;
}

element normal.urgent {
    background-color:            @urgent;
    text-color:                  @foreground;
}

element normal.active {
    background-color:            @active;
    text-color:                  @foreground;
}

element selected.normal {
    background-color:            @selected;
    text-color:                  @foreground;
}

element selected.urgent {
    background-color:            @urgent;
    text-color:                  @foreground;
}

element selected.active {
    background-color:            @urgent;
    text-color:                  @foreground;
}

element-icon {
    background-color:            transparent;
    text-color:                  inherit;
    size:                        14px;
    cursor:                      inherit;
}

element-text {
    background-color:            transparent;
    text-color:                  inherit;
    cursor:                      inherit;
    vertical-align:              5.5;
    horizontal-align:            0.0;
}
EOF
}

# Initialize arrays
WALLPAPERS=()
FILENAMES=()

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>"$LOG_FILE"
}

# Find wallpapers safely
while IFS= read -r -d $'\0' file; do
    WALLPAPERS+=("$file")
    BASENAME=$(basename "$file")
    FILENAME_WITHOUT_EXT="${BASENAME%.*}"
    CAPITALIZED_NAME=$(echo "$FILENAME_WITHOUT_EXT" | sed 's/\b\(.\)/\u\1/g')
    FILENAMES+=("$CAPITALIZED_NAME")
done < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -print0 2>/dev/null)

# If no wallpapers are found, exit the script
if [ ${#FILENAMES[@]} -eq 0 ]; then
    log "No wallpapers found in $WALLPAPER_DIR"
    exit 1
fi

# Select wallpaper using sxiv, dmenu, or rofi
if command -v rofi >/dev/null 2>&1; then
    generate_rasi_config
    SELECTED_NAME=$(printf "%s\n" "${FILENAMES[@]}" | rofi -dmenu -p "Select a wallpaper" -theme "/tmp/wallpaper_switcher_style.rasi")
    # Map the selected name back to the corresponding full path
    for i in "${!FILENAMES[@]}"; do
        if [ "${FILENAMES[$i]}" = "$SELECTED_NAME" ]; then
            SELECTED="${WALLPAPERS[$i]}"
            break
        fi
    done
elif command -v sxiv >/dev/null 2>&1; then
    # Use sxiv in selection mode
    SELECTED=$(printf "%s\n" "${WALLPAPERS[@]}" | sxiv -tio - 2>/dev/null | head -n1)
    if [ -n "$SELECTED" ]; then
        BASENAME=$(basename "$SELECTED")
        FILENAME_WITHOUT_EXT="${BASENAME%.*}"
        SELECTED_NAME=$(echo "$FILENAME_WITHOUT_EXT" | sed 's/\b\(.\)/\u\1/g')
        log "Selected via sxiv: $SELECTED"
    else
        log "No selection made in sxiv"
    fi
elif command -v dmenu >/dev/null 2>&1; then
    SELECTED_NAME=$(printf "%s\n" "${FILENAMES[@]}" | dmenu -l 15 -i -p "Select a wallpaper")
    # Map the selected name back to the corresponding full path
    for i in "${!FILENAMES[@]}"; do
        if [ "${FILENAMES[$i]}" = "$SELECTED_NAME" ]; then
            SELECTED="${WALLPAPERS[$i]}"
            log "Selected via dmenu: $SELECTED"
            break
        fi
    done
else
    log "Error: Neither rofi, sxiv nor dmenu could be found."
    exit 1
fi

# If user cancelled selection, exit
if [ -z "$SELECTED" ]; then
    log "No wallpaper selected."
    exit 0
fi

# log "Selected wallpaper: $SELECTED"

# If a wallpaper was selected, update the sway config and reload sway
if [ -n "$SELECTED" ]; then
    # Update the sway configuration file
    if sed -i "s|^output \* bg .*|output \* bg $SELECTED fill|" "$SWAY_CONFIG"; then
        # Reload Sway to apply the changes
        swaymsg reload
    else
        log "Error: Failed to update sway config"
        exit 1
    fi
else
    log "Selected wallpaper not found: $SELECTED_NAME"
fi
